# Environment Settings
gpu_id: '0, 1, 2, 3, 4, 5, 6, 7'
use_gpu: True

# Model Settings
embedding_size: 64

# Training Settings
epochs: 300
train_batch_size: 4096
train_neg_sample_args:
    distribution: uniform
    sample_num: 1
    alpha: 1.0
    dynamic: False
    candidate_num: 0
valid_metric: MRR@10

# Evaluation Settings
eval_batch_size: 4096
eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.9,0.05,0.05]}
    mode: full
metric_decimal_place: 4
topk: 10