# ----- Steam specific settings -----
# Basic Information
USER_ID_FIELD: user_id
ITEM_ID_FIELD: product_id
RATING_FIELD: play_hours
TIME_FIELD: timestamp
load_col:
    inter: [user_id, product_id, play_hours, timestamp]

# Common Features
seq_len:
  genres: 10
  specs: 5
  tags: 10