# Environment Settings
gpu_id: '0, 1, 2, 3, 4, 5, 6, 7'
use_gpu: True
workers: 2

# Model Settings
embedding_size: 64

# Training Settings
epochs: 300
train_batch_size: 8192
train_neg_sample_args:
  distribution: uniform
  sample_num: 1
  alpha: 1.0
  dynamic: False
  candidate_num: 0
valid_metric: MRR@10
eval_step: 5

# Evaluation Settings
eval_batch_size: 4096000
eval_args:
  group_by: user
  order: RO
  split: { 'RS': [ 0.8,0.1,0.1 ] }
  mode: uni100
metric_decimal_place: 4
topk: 10

# ----- Steam specific settings -----
# Basic Information
USER_ID_FIELD: user_id
ITEM_ID_FIELD: product_id
RATING_FIELD: play_hours
TIME_FIELD: timestamp
load_col:
    inter: [user_id, product_id, play_hours, timestamp]

# Common Features
seq_len:
  genres: 10
  specs: 5
  tags: 10